### ISSUE TITLE
Mr-plow shall support Go  Standard project layout.

### ISSUE THREAD

**Issue by giorgiozoppi** [Ringloop/mr-plow#41]
It would be interesting having the standard project layout for this project.
As a reference: https://github.com/golang-standards/project-layout

**Comment by giorgiozoppi** [comment]
I mean i need to your approval to move the project following the community standards.

**Comment by DarioBalinzo** [comment]
I will take a look soon

**Comment by feed3r** [comment]
I just had a look and it's ok for me. Anyway, as I wrote on the comment, I would wait a confirmation by @DarioBalinzo

**Comment by giorgiozoppi** [comment]
@feed3r  thank you.

**Comment by giorgiozoppi** [comment]
Fixed we can close this:
